version: '3.4'

services:
  mongodb:
    image: mongo
    ports:
        - 27017:27017
    volumes:
        - ./database:/data/db

  trackservice:
    image: ${DOCKER_REGISTRY-}trackservice
    build:
      context: .
      dockerfile: TrackService/Dockerfile
